---
title: "Plots - Relationship with Gamble Decisions"
author: "Johnny Lau"
date: "24/03/2020"
output: html_document
---
# Result plots markdown {.tabset}  
The RainCloudPlot function used here was created by Allen et al (2019).  
DOI: 10.12688/wellcomeopenres.15191.1  
It can be downloaded here (https://github.com/RainCloudPlots/RainCloudPlots)

```{r, include=FALSE}
#{r setup, include=FALSE, cache=TRUE, echo=FALSE}

#remove all existing variables in the environment
rm(list=ls())

current_dir = "C:/Users/DrJKLau/Desktop/BehData_curi-fmri_osf"
setwd(current_dir)

```

## Setup and data prep 
Load packages and data

```{r load packages and data}

require(pacman)

# Read into the data for analysis
df <- read.csv(file = 'data1_initial_behav.csv', header=TRUE, sep=",")

knitr::opts_chunk$set(cache=T)

# check if a package is installed and then load it
p_load(ggplot2)
p_load(cowplot)
p_load(dplyr)
p_load(readr)
p_load(lme4)

# Read R code from another file
source("R_rainclouds.R")  
#this R_rainclouds plot function is downloaded from https://github.com/RainCloudPlots/RainCloudPlots



```

## RainCloudPlot {.tabset}
### Preparing a theme 
Setting up a theme for the plot (Relationship beween Stimulus Rating and Gamble Decisions)
```{r plot design}


raincloud_theme <- theme(
  #text = element_text(size = 10),
  axis.title.x = element_blank(), 
  axis.title.y = element_text(size="10", face="bold", color="black", margin = margin(t = 0, r = 4)), 
  axis.text.x = element_text(size = 9, face="bold", margin = margin(t = 10, r = 0, b = 0, l = 15), colour = 'black'),
  axis.text.y = element_text(size = 9,  margin = margin(t = 0, r = 5, b = 0, l = 0), colour = 'black'),
  legend.title=element_text(size=10),
  legend.text=element_text(size=8),
  legend.position = 'bottom',   
  #plot.title = element_text(lineheight=.8, face="bold", size = 16),
  panel.border = element_blank(),
  panel.background = element_blank(),
  panel.grid.minor = element_blank(),
  panel.grid.major = element_blank(), 
  axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
  axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'),
  axis.ticks.length = unit(0, "cm")) 


```

### Re-structuring the data
```{r data wrangling}

# Using 'aggregate', split data into subsets computing summary statistics for each
  # raw_rate: raw rating of curiosity and desirability for food
  # category: food or magic (or trivia in one of the fMRI experiments)
  # choice/decision:  1 for accepted; 0 for rejected
agg_ppt_data <- aggregate(raw_rate~participant+category+choice, data=df, FUN=mean)

# re-label choice/decision options
agg_ppt_data["Decision"] <-NA
agg_ppt_data$Decision[agg_ppt_data$choice==0] <- "Reject"
agg_ppt_data$Decision[agg_ppt_data$choice==1] <- "Accept"


# compile Mean, SD, & SE of ratings across participants into a DataFrame
rst_m <- aggregate(raw_rate~category+choice, data=df, FUN=mean)
names(rst_m)[3]<- "group_mean_rate"

rst_sd <-  aggregate(raw_rate~category+choice, data=df, FUN=sd)  
names(rst_sd)[3]<- "sd_rate"
rst <- merge(rst_m, rst_sd, by = c("category", "choice"))


rst["se_rate"] <- rst$sd_rate/sqrt(length(unique(df$participant)))

# re-label choice/decision options
rst["Decision"] <-NA
rst$Decision[rst$choice==0] <- "Reject"
rst$Decision[rst$choice==1] <- "Accept"

# also compute the ymin and ymax of the error bars using SE of ratings
rst$ymin = with(rst, group_mean_rate - se_rate)
rst$ymax = with(rst, group_mean_rate + se_rate)




```

### Plotting
```{r, message=FALSE}

#use ggplot and R_rainclouds.script (esp 'geom_flat_violin' function) for plotting
g_cloudplot <- ggplot() + 
  geom_flat_violin(data = agg_ppt_data, aes(y = raw_rate, x = category, fill=Decision), position = position_nudge(x = .2, y = 0), alpha = .6, colour=FALSE, show.legend = FALSE) +
  # add data-points (average ppt rating of each participant)
  geom_point(data=agg_ppt_data, aes(y = raw_rate, x = category, color = Decision), position = position_jitter(width=.1),size = 1.5, alpha = 0.8, show.legend = FALSE, shape=16) +
  # add the summary scores (average rating across participants for each condition )
  geom_pointrange (data=rst, aes(y = group_mean_rate, x = category, ymin= ymin, ymax= ymax, color=Decision), shape=16, size=1.2, position = position_dodge(width=0.1)) + 
  
  # adjust other plot features
  raincloud_theme + 
  scale_x_discrete(labels=c("Curiosity","Food Desirability")) +
  ylim(0,7) +
  labs(fill = "Decision") +
  scale_y_continuous(name="Acceptance Rate")

g_cloudplot

# Try the following line to save the plot as an image
#ggsave("RCP_initialbeh.jpeg", width = 140, height = 180, units = "mm", dpi=300, limitsize=FALSE)

```


